version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: ca_postgres
    environment:
      POSTGRES_USER: siddhantchasta
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: courseallocator
    ports:
      - "5435:5432"  

  redis:
    image: redis:7-alpine
    container_name: ca_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ca_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"